various cleanups suggested by lintian

diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -1,9 +1,10 @@
 #!/bin/sh
-# don't set -e, because removal stuff like defoma may fail, but we're
-# still successfully uninstalled.
-# set -e
 
 #DEBHELPER#
+
+# don't set -e before debhelper, because removal stuff like defoma may fail,
+# but we're still successfully uninstalled.
+set -e
 
 if [ "$1" = "remove" ] && [ -e /var/lib/msttcorefonts/ms-fonts ]; then
 	cd /usr/share/fonts/truetype/msttcorefonts && \
