Remove set -e from prerm, because if msttcorefonts is not properly installed defoma-font may fail and we're still well uninstalled. (Closes: #461926)

diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -1,14 +1,16 @@
 #!/bin/sh
-set -e
+# don't set -e, because removal stuff like defoma may fail, but we're
+# still successfully uninstalled.
+# set -e
 
 #DEBHELPER#
 
 if [ "$1" = "remove" ] && [ -e /var/lib/msttcorefonts/ms-fonts ]; then
-        cd /usr/share/fonts/truetype/msttcorefonts
-	rm -f `cat /var/lib/msttcorefonts/ms-fonts`
+	cd /usr/share/fonts/truetype/msttcorefonts && \
+		rm -f `cat /var/lib/msttcorefonts/ms-fonts`
 	rm -f '/usr/share/doc/msttcorefonts/READ_ME!.gz'
-        rm -r /var/lib/msttcorefonts/ms-fonts
-        rmdir --ignore-fail-on-non-empty /usr/share/fonts/truetype/msttcorefonts
+	rm -r /var/lib/msttcorefonts/ms-fonts
+	rmdir --ignore-fail-on-non-empty /usr/share/fonts/truetype/msttcorefonts
 fi
 
 exit 0
